name: Deploy to Google Cloud Functions

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Build with Maven
        run: mvn clean package

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          version: 'latest'
          service_account_key: ${{ secrets.GCP_SA_KEY }}
       
      - name: 'Authenticate via SAKE'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Deploy to Cloud Functions
        run: |
          gcloud functions deploy resume-api \
            --entry-point org.example.HelloHttpFunction \
            --runtime java11 \
            --trigger-http \
            --allow-unauthenticated \
            --region asia-south1 \
            --project precise-tube-429809-s4 \
            --memory 512MB \
            --timeout 90s \
            --min-instances 0 \
            --max-instances 1 \
            --service-account firestore-poc@precise-tube-429809-s4.iam.gserviceaccount.com